version: '3.9'
services:
  hardhatsrc:
    container_name: hardhatsrc_container
    build: ./docker/src
    ports: 
      - 13089:3000
      - 16089:6006
      - 8545:8545
    volumes: 
      - ./src:/src/
    stdin_open: true
    tty: true
    environment: 
      - TZ=Asia/Tokyo
    networks: 
      - default

networks:
  default:
